---
:mongo:
  :host: localhost
  :port: 27017
  :database: vindiniminer
  #:auth:         # Uncomment to enable auth
    #:username:
    #:password:
# :rate_limit: 
:collections:
  :index: vindindex
:announce_url: http://vindinium.org/now-playing       # Where to get the JSON list of hashes
:event_url: http://vindinium.org/events/              # Where to get events
:retry_delay: 120  # Wait n seconds before retrying if the connection is dropped.
:event_download_delay: 60 # Wait n seconds between event stream downloads.
